### ISSUE TITLE
Unable to indicate misa register not implemented

### ISSUE THREAD

**Issue by dthakkar-ventana** [riscv/riscv-config#14]
Table 3.2 of the privileged architecture (both the ratified version and the 2020/01/25 draft) states a value of 0 can be returned to indicate misa register is not implemented. The way to represent this would be to set both “default” and “bitmask” fields to 0, along with the “implemented” field to “false”. The SchemaValidator doesn’t allow for this and errors out based on the three way XOR of default, bitmask and ISA string.

**Comment by cr1901** [comment]
FWIW, it currently seems [impossible](https://github.com/riscv-software-src/riscv-config/blob/b550aaa38538797b6f63aba2e2385c83642f6756/riscv_config/schemaValidator.py#L116-L117) to indicate `misa` is unimplemented in the most recent commit without [running afoul](https://github.com/riscv-software-src/riscv-config/blob/b550aaa38538797b6f63aba2e2385c83642f6756/riscv_config/schemaValidator.py#L304-L316) of a later check.

At the very least, _I_ can't get past the "reset value does not match with extensions enabled" check with the following:

```
  misa:
   reset-val: 0
   rv32:
     accessible: true
     mxl:
      implemented: false
     extensions:
      implemented: false
```
