### ISSUE TITLE
defining mtval informative and unconditional writes

### ISSUE THREAD

**Issue by neelgala** [riscv/riscv-config#16]
According to the Spec mtval is a WARL field. However, a platform has a luxury to completely specify which exceptions must set mtval informatively and which may unconditionally set it to zero. To capture this the following is proposed:

1. Extend CSR template with a ``platform`` field:
We add a boolean field ``platform`` to each csr which indicates if the platform-yaml 
has more information on the same node. The platform yaml should also contain a node with the same csr-name. The node in the isa-yaml will define the set of all legal/illegal values that mtval can take

2. Adding mtval node in platform-yaml:
the mtval field in the platform yaml could be :
```
mtval:
  implemented: True
  behaviour:
    - [0, [0x00000000:0xFFFFFFFF] , "Address that was misaligned"]
    - [2, [0x00000000, 0x0000FFFF] , "lower 16-bits of Instruction that was illegal"]
```
Each entry under behaviour is a 3 element tuple. The first element is cause value, the second defines the set of legal values and the last element is the description.
Cause values missing in the behavior list are assumed to write "0" to mtval by default.

**Comment by stnolting** [comment]
Is this still up-to-date? 🤔

I am trying to constrain the behavior of `mtval`. This is my entry in `*_platform.yaml`:
```yml
mtval_condition_writes:
 implemented: true
 behaviour:
   - [0, [0x00000000:0xFFFFFFFF], "Instruction fetch - address that was misaligned"]
   - [1, [0x00000000:0xFFFFFFFF], "Instruction fetch - address that triggered a bus exception"]
   - [4, [0x00000000:0xFFFFFFFF], "Load access - address that was misaligned"]
   - [5, [0x00000000:0xFFFFFFFF], "Load access - address that triggered a bus exception"]
   - [6, [0x00000000:0xFFFFFFFF], "Store access - address that was misaligned"]
   - [7, [0x00000000:0xFFFFFFFF], "Store access - address that triggered a bus exception"]
```

But I'm getting an error here:
```
   ERROR |  mtval_condition_writes:
   ERROR |   behaviour:must be of dict type
```

What exactly is a "dict type"? The only thing I could find is https://riscv-config.readthedocs.io/en/stable/yaml-specs.html?highlight=dictionary#mtval-condition-writes but I don't really understand the documentation there 😅
I would be happy for any kind of help :)

**Comment by pawks** [comment]
I believe this has not been implemented yet. A temporary way of using this for now would be do something like the following 
```
mtval_condition_writes:
  implemented: true
  behaviour:
    e0: "[0x00000000:0xFFFFFFFF], 'Instruction fetch - address that was misaligned']"
    e1: "[0x00000000:0xFFFFFFFF], 'Instruction fetch - address that triggered a bus exception']"
    ....
```
